baseURL = "https://katachin.github.io/hugotest/"
languageCode = "ja-JP"
title = "テストン"
publishDir = "docs"

theme = "ananke"
# x theme = "starter-academic"
# x theme = "hugo-theme-iris"
# x theme = "doks"
# theme = "kiss"
# theme = "hugo-eureka"
# theme = "anatole"
# x theme = "hugo-theme-terminal"
# theme = "toha"
# theme = "hugo-theme-dream"
# theme = "hugo-paper"
# theme = "hugo-theme-introduction"
# theme = "hugo-theme-lean-launch-page"
# theme = "hugo-profile"
# x theme = "uBlogger"
# x theme = "docsy"
# theme = "capsule"
# theme = "hugo-PaperMod"
# theme = "hugo-theme-fuji"
# theme = ""
# theme = ""
# theme = ""

[params]
# featured_image = "/images/gohugo-default-sample-hero-image.jpg"
featured_image = "/images/orange720x320@.png"
# featured_image = "/images/test.png"
